site_name: Sisitech Docs

theme:
  name: material
  logo: sisitech-logo.png
  favicon: sisitech-logo.png
  features:
    - navigation.top
    - navigation.instant

plugins:
    - search
    - mermaid2
    
extra_css:
  - css/extra.css
  - https://cdn.jsdelivr.net/gh/knsv/mermaid@6.0.0/dist/mermaid.css


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets 
  