site_name: Sisitech Docs

theme:
  name: material
  logo: sisitech-logo.png
  favicon: sisitech-logo.png
extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
